/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import static main.OOM.*;

/**
 *
 * @author harsh
 */
public class AddEdge extends javax.swing.JFrame {

    /**
     * Creates new form AddEdge
     */
    
    public AddEdge() {
        initComponents();
        String[] A = new String[OOM.G.getV().size()];
        for (int i = 0; i < OOM.G.getV().size(); i++) {
            A[i] = OOM.G.getV().get(i).getName();
        }
        fromVertex.setModel(new javax.swing.DefaultComboBoxModel<>(A));
        toVertex.setModel(new javax.swing.DefaultComboBoxModel<>(A));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VertexNameF = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        addEdge = new javax.swing.JButton();
        VertexNameT = new javax.swing.JLabel();
        Weight = new javax.swing.JLabel();
        fromVertex = new javax.swing.JComboBox<>();
        toVertex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add  Edge");

        VertexNameF.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        VertexNameF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VertexNameF.setText("FromVertex");

        weight.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        addEdge.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        addEdge.setText("AddEdge");
        addEdge.setActionCommand("AddEdge");
        addEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeActionPerformed(evt);
            }
        });

        VertexNameT.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        VertexNameT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VertexNameT.setText("ToVertex");

        Weight.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        Weight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Weight.setText("Weight");

        fromVertex.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        fromVertex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FromVertex" }));

        toVertex.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        toVertex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "toVertex" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VertexNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(toVertex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VertexNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fromVertex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(addEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VertexNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VertexNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed
    
   

    private void addEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeActionPerformed
        String from = (String) fromVertex.getSelectedItem();
        String to = (String) toVertex.getSelectedItem();
        String w = weight.getText();
        if (from.equals(to)) {
            JOptionPane.showMessageDialog(null, "Please Enter FromVertex and ToVertex Different\n");

        } else {
            try {
                double weight = Double.parseDouble(w);
                Vertex V = OOM.G.searchVertex(from);
                Vertex V1 = OOM.G.searchVertex(to);
                OOM.G.checkEdge(from, to);
                OOM.G.addEdge(from, to,weight);
                JOptionPane.showMessageDialog(null, "Adding Successfull");
//                this.dispose();

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please Enter the Correct Weight");
            } catch (Invalid e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }


    }//GEN-LAST:event_addEdgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEdge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VertexNameF;
    private javax.swing.JLabel VertexNameT;
    private javax.swing.JLabel Weight;
    private javax.swing.JButton addEdge;
    private javax.swing.JComboBox<String> fromVertex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> toVertex;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
