/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import java.io.FileNotFoundException;
import static java.lang.System.exit;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harsh
 */
public class ImportFile extends javax.swing.JFrame {

    /**
     * Creates new form ImportFile
     */
    public ImportFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        File = new javax.swing.JTextField();
        Import = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Import Your Graph");

        File.setText("/home/harsh/NetBeansProjects/OOM/src/main/input");
        File.setToolTipText("");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        Import.setText("Import");
        Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Import, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(File, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Import)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileActionPerformed

    private void ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportActionPerformed
        // TODO add your handling code here:
        String name = File.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill all Fields");
        } else {

            File file = new File(name);
            try {
                Vertex V = null;
                Scanner scan = new Scanner(file);
                int nv = scan.nextInt();
                System.out.print(nv);
                scan.nextLine();
                for (int i = 0; i < nv; i++) {
                    String s = scan.nextLine();
                    String[] input = s.split(" ");
                    try {
                        int xx = Integer.parseInt(input[1]);
                        int yy = Integer.parseInt(input[2]);
                        V = new Vertex(input[0], xx, yy);
                        try {
                            OOM.G.searchVertex(V);
                            OOM.G.addVertex(V);
//                    JOptionPane.showMessageDialog(null, "Vertex is Added");
//                            System.out.println(V + " Vertex is Added");

                        } catch (Invalid e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                            exit(0);
                            System.out.println(e.getMessage());

                        }

                    } catch (NumberFormatException e) {

                        JOptionPane.showMessageDialog(null, "Please Enter Coordinates Correctly");
                        exit(0);
                        System.out.println(e.getMessage());

                    }catch(ArrayIndexOutOfBoundsException ee){
                        JOptionPane.showMessageDialog(null, "Vertex Does Not Match the Required Format");
                        System.out.println(ee.getMessage());
                        exit(0);
                    }
                }
                int ne = scan.nextInt();
                scan.nextLine();
                for (int i = 0; i < ne; i++) {
                    String s = scan.nextLine();
                    String[] input = s.split(" ");
                    String from = input[0];
                    String to = input[1];
                    String w = input[2];
                    if (from.equals(to)) {
                        JOptionPane.showMessageDialog(null, "Please Enter FromVertex and ToVertex Different\n");
                        System.out.println("Please Enter FromVertex and ToVertex Different\n");

                    } else {
                        try {
                            double weight = Double.parseDouble(w);
                            OOM.G.searchVertex(from);
                            OOM.G.searchVertex(to);
                            OOM.G.checkEdge(from, to);
                            OOM.G.addEdge(from, to, weight);
//                    JOptionPane.showMessageDialog(null, "Adding Successfull");
                            System.out.println("Adding Successfull");

                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "Please Enter the Correct Weight");
                            exit(0);
                            System.out.println("Please Enter the Correct Weight");

                        } catch (Invalid e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                            exit(0);
                            System.out.println(e.getMessage());

                        }catch(ArrayIndexOutOfBoundsException ee){
                        JOptionPane.showMessageDialog(null, "Input Does Not Match The Required Format");
                        System.out.println(ee.getMessage());
                        exit(0);
                    }
                    }
                }
                JOptionPane.showMessageDialog(null,"Input Taken");
                this.dispose();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "File Not Found");
                this.dispose();
            }

        }

    }//GEN-LAST:event_ImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField File;
    private javax.swing.JButton Import;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
