/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author harsh
 */
public class ModifyEdge extends javax.swing.JFrame {

    /**
     * Creates new form ModifyEdge
     */
    public ModifyEdge() {
        initComponents();
        String[] A = new String[OOM.G.getV().size()];
        for (int i = 0; i < OOM.G.getV().size(); i++) {
            A[i] = OOM.G.getV().get(i).getName();
        }
        fromVertex.setModel(new javax.swing.DefaultComboBoxModel<>(A));
        toVertex.setModel(new javax.swing.DefaultComboBoxModel<>(A));;
        fromVertex1.setModel(new javax.swing.DefaultComboBoxModel<>(A));
        toVertex1.setModel(new javax.swing.DefaultComboBoxModel<>(A));;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toVertex = new javax.swing.JComboBox<>();
        VertexNameF = new javax.swing.JLabel();
        SearchEdge = new javax.swing.JButton();
        VertexNameT = new javax.swing.JLabel();
        fromVertex = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        toVertex1 = new javax.swing.JComboBox<>();
        VertexNameF1 = new javax.swing.JLabel();
        VertexNameT1 = new javax.swing.JLabel();
        fromVertex1 = new javax.swing.JComboBox<>();
        Weight = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        ModifyEdge = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        toVertex.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        toVertex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "toVertex" }));

        VertexNameF.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        VertexNameF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VertexNameF.setText("FromVertex");

        SearchEdge.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        SearchEdge.setText("SearchEdge");
        SearchEdge.setToolTipText("");
        SearchEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEdgeActionPerformed(evt);
            }
        });

        VertexNameT.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        VertexNameT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VertexNameT.setText("ToVertex");

        fromVertex.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        fromVertex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FromVertex" }));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modify Your Edge");

        toVertex1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        toVertex1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "toVertex" }));

        VertexNameF1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        VertexNameF1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VertexNameF1.setText("NewFromVertex");

        VertexNameT1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        VertexNameT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VertexNameT1.setText("NewToVertex");

        fromVertex1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        fromVertex1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FromVertex" }));
        fromVertex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromVertex1ActionPerformed(evt);
            }
        });

        Weight.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        Weight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Weight.setText("NewWeight");

        weight.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        ModifyEdge.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        ModifyEdge.setText("ModifyEdge");
        ModifyEdge.setEnabled(false);
        ModifyEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyEdgeActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Ubuntu", 2, 16)); // NOI18N
        jToggleButton1.setText("Reset");
        jToggleButton1.setToolTipText("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(weight))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(VertexNameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(toVertex1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(VertexNameF1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fromVertex1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModifyEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(VertexNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(toVertex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(VertexNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fromVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(118, 118, 118))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(SearchEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VertexNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VertexNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VertexNameF1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromVertex1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VertexNameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toVertex1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ModifyEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEdgeActionPerformed
        String from = (String) fromVertex.getSelectedItem();
        String to = (String) toVertex.getSelectedItem();

        if (from.equals(to)) {
            JOptionPane.showMessageDialog(null, "Please Enter FromVertex and ToVertex Different\n");

        } else {
            try {

                Vertex V = OOM.G.searchVertex(from);
                Vertex V1 = OOM.G.searchVertex(to);
                OOM.G.checkEdge(from, to);
                JOptionPane.showMessageDialog(null, "Edge Not Found");

            } catch (Invalid e) {
                double w = OOM.G.getWeight(from, to);
                JOptionPane.showMessageDialog(null, "Edge Found\nFromVertex: " + from + "\nToVertex: " + to + "\nWeight: " + w);
                fromVertex.setEnabled(false);
                toVertex.setEnabled(false);
                ModifyEdge.setEnabled(true);

            }
        }
    }//GEN-LAST:event_SearchEdgeActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void ModifyEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyEdgeActionPerformed
        String from1 = (String) fromVertex.getSelectedItem();
        String to1 = (String) toVertex.getSelectedItem();
        String from = (String) fromVertex1.getSelectedItem();
        String to = (String) toVertex1.getSelectedItem();
        String w = weight.getText();
        if (from.equals(to)) {
            JOptionPane.showMessageDialog(null, "Please Enter FromVertex and ToVertex Different\n");

        } else {
            try {
                double weight = Double.parseDouble(w);
                Vertex V = OOM.G.searchVertex(from);
                Vertex V1 = OOM.G.searchVertex(to);
                if (from.equals(from1) && to.equals(to1)) {
                } else {
                    OOM.G.checkEdge(from, to);
                }
                OOM.G.deleteEdge(from1, to1);
                OOM.G.addEdge(from, to, weight);
                JOptionPane.showMessageDialog(null, "Modification Successfull");
                ModifyEdge.setEnabled(false);
                SearchEdge.setEnabled(true);
                fromVertex.setEnabled(true);
                toVertex.setEnabled(true);
//                this.dispose();

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please Enter the Correct Weight");
            } catch (Invalid e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_ModifyEdgeActionPerformed

    private void fromVertex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromVertex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromVertex1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        ModifyEdge.setEnabled(false);
        SearchEdge.setEnabled(true);
        fromVertex.setEnabled(true);
        toVertex.setEnabled(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyEdge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModifyEdge;
    private javax.swing.JButton SearchEdge;
    private javax.swing.JLabel VertexNameF;
    private javax.swing.JLabel VertexNameF1;
    private javax.swing.JLabel VertexNameT;
    private javax.swing.JLabel VertexNameT1;
    private javax.swing.JLabel Weight;
    private javax.swing.JComboBox<String> fromVertex;
    private javax.swing.JComboBox<String> fromVertex1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> toVertex;
    private javax.swing.JComboBox<String> toVertex1;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
